### ISSUE TITLE
is this a typo, shouldn't it be msg.type and not msg.tp

### ISSUE THREAD

**Issue by japrogramer** [steelkiwi/aiohttp_test_chat#2]
https://github.com/steelkiwi/aiohttp_test_chat/blob/master/chat/views.py#L40

I think I found a typo, I believe it needs to be msg.type and not msg.tp
this occurs many times in the file.

**Comment by congnghiakhiem** [comment]
__version__ = '3.4.4'

D:\test\aiohttp_test_chat>python app.py
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    from routes import routes
  File "D:\test\aiohttp_test_chat\routes.py", line 1, in <module>
    from chat.views import ChatList, WebSocket
  File "D:\test\aiohttp_test_chat\chat\views.py", line 3, in <module>
    from aiohttp import web, MsgType
ImportError: cannot import name 'MsgType' from 'aiohttp' (C:\Python37\lib\site-packages\aiohttp\__init__.py)
